name=input("enter name : ")
birthmonth=input("enter birth month : ")
day=int(input("enter day of your birthday :"))
year=int(input("enter year of your birthday :"))
print(name , "your birthday is on " , birthmonth , day , " , " , year ,"!")